version: "3.7"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clients

  jobmanager:
    image: flink:1.15.1-scala_2.12
    volumes:
      - ./libs/flink-table-store-dist-0.2.0.jar:/opt/flink/lib/flink-table-store-dist-0.2.0.jar
      - ./libs/postgresql-42.5.0.jar:/opt/flink/lib/postgresql-42.5.0.jar
      - ./libs/flink-connector-jdbc-1.15.2.jar:/opt/flink/lib/flink-connector-jdbc-1.15.2.jar
      - ./libs/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: flink:1.15.1-scala_2.12
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - |
        FLINK_PROPERTIES=
        taskmanager.numberOfTaskSlots: 8
        parallelism.default: 1
  kafka:
    image: confluentinc/cp-kafka:6.1.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "29092:29092"
      - "9092:9092"

    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
     - "2181:2181"